title: OpoLua
tagline: Runtime and Viewer for EPOC Programs and Files
baseurl: ""
url: ""

plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-environment-variables
  - jekyll-gfm-admonitions
destination: ../_site

toc:
  ordered_list: true

defaults:
  - values:
      layout: "default"
  - scope:
      path: "docs"
    values:
      layout: "documentation"
      toc: true
      shows_title: true
  - scope:
      path: "faq"
    values:
      layout: "documentation"
      toc: true
      shows_title: true
